# Generated by Django 3.1.7 on 2021-03-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210228_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecommendation',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
